spring:
  application:
    name: DevSquard
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devsquad_db
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never
  upload:
    location: C://Users//WD//Desktop//post-image
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  security:
    user:
      name: devsquad
      password: 1234

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
